CorrespondenceGenerator:
  _target_: gtsfm.frontend.correspondence_generator.det_desc_correspondence_generator.DetDescCorrespondenceGenerator

  detector_descriptor:
    # _target_: gtsfm.frontend.cacher.detector_descriptor_cacher.DetectorDescriptorCacher
    # detector_descriptor_obj:
    _target_: gtsfm.frontend.detector_descriptor.disk.DiskDetectorDescriptor
    max_keypoints: 8000

  matcher:
    # _target_: gtsfm.frontend.cacher.matcher_cacher.MatcherCacher
    # matcher_obj:
    _target_: gtsfm.frontend.matcher.lightglue_matcher.LightGlueMatcher
    features: "disk"
